# This docker-compose file is for local development only
version: '3.4'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sequelize-demo
    ports:
      - target: 3306
        published: 3307
        mode: host
